### PR TITLE
update devbuild.sh

### PR DESCRIPTION
**Pull request by guoqing-noaa**

### CODE REVIEW

**Review by chunhuazhou — COMMENTED** [review]
This will involve change to the file build.comgsi, right?

**Comment by guoqing-noaa** [comment]
I also made a PR to your GSI branch (actually it was earlier than this PR).
https://github.com/chunhuazhou/GSI/pull/1/files

**Comment by chunhuazhou** [comment]
> I also made a PR to your GSI branch (actually it was earlier than this PR). https://github.com/chunhuazhou/GSI/pull/1/files

Okay, I see. Somehow I didn't get the email notifications. Do I need to test it? Or have you already tested it? Does it work on Hera when we don't have "kjet"? Thank you!

**Comment by guoqing-noaa** [comment]
I tested on Jet. It should works on Hera as kjet is an optional parameter and does not affect other platforms. 
You may want to merge GSI first and then merge this. 
The GSI hash needs to be updated for ufs-srweather-app.

**Comment by chunhuazhou** [comment]
> I tested on Jet. It should works on Hera as kjet is an optional parameter and does not affect other platforms. You may want to merge GSI first and then merge this. The GSI hash needs to be updated for ufs-srweather-app.

Sounds good! I am testing the compile on Hera. Once it is done, I will add the GSI hash to this PR too. Thank you very much!

**Comment by chunhuazhou** [comment]
Thank you @guoqing-noaa for working on this!

**Pull request merged**
